const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
const ADD_CART_ITEM_FAILURE = "ADD_CART_ITEM_FAILURE";
const GET_CART_ITEM_REQUEST = "GET_CART_ITEM_REQUEST";
const GET_CART_ITEM_SUCCESS = "GET_CART_ITEM_SUCCESS";
const GET_CART_ITEM_FAILURE = "GET_CART_ITEM_FAILURE";
const SHOW_CART_REQUEST = "SHOW_CART_REQUEST";
const SHOW_CART_SUCCESS = "SHOW_CART_SUCCESS";
const SHOW_CART_FAILURE = "SHOW_CART_FAILURE";
const HIDE_CART_REQUEST = "HIDE_CART_REQUEST";
const HIDE_CART_SUCCESS = "HIDE_CART_SUCCESS";
const HIDE_CART_FAILURE = "HIDE_CART_FAILURE";

export {
  ADD_CART_ITEM_REQUEST,
  ADD_CART_ITEM_SUCCESS,
  ADD_CART_ITEM_FAILURE,
  GET_CART_ITEM_REQUEST,
  GET_CART_ITEM_SUCCESS,
  GET_CART_ITEM_FAILURE,
  SHOW_CART_REQUEST,
  SHOW_CART_SUCCESS,
  SHOW_CART_FAILURE,
  HIDE_CART_REQUEST,
  HIDE_CART_SUCCESS,
  HIDE_CART_FAILURE,
};
