const GET_INFO_PRODUCT_REQUEST = "GET_INFO_PRODUCT_REQUEST";
const GET_INFO_PRODUCT_SUCCESS = "GET_INFO_PRODUCT_SUCCESS";
const GET_INFO_PRODUCT_FAILURE = "GET_INFO_PRODUCT_FAILURE";
const ADD_COMMENT_PRODUCT_REQUEST = "ADD_COMMENT_PRODUCT_REQUEST";
const ADD_COMMENT_PRODUCT_SUCCESS = "ADD_COMMENT_PRODUCT_SUCCESS";
const ADD_COMMENT_PRODUCT_FAILURE = "ADD_COMMENT_PRODUCT_FAILURE";

export {
  GET_INFO_PRODUCT_REQUEST,
  GET_INFO_PRODUCT_SUCCESS,
  GET_INFO_PRODUCT_FAILURE,
  ADD_COMMENT_PRODUCT_REQUEST,
  ADD_COMMENT_PRODUCT_SUCCESS,
  ADD_COMMENT_PRODUCT_FAILURE,
};
