const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export { CREATE_ORDER_REQUEST, CREATE_ORDER_SUCCESS, CREATE_ORDER_FAILURE };
