const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
const GET_PRODUCT_FILTER_REQUEST = "GET_PRODUCT_FILTER_REQUEST";
const GET_PRODUCT_FILTER_SUCCESS = "GET_PRODUCT_FILTER_SUCCESS";
const GET_PRODUCT_FILTER_FAILURE = "GET_PRODUCT_FILTER_FAILURE";
const GET_SEARCH_PRODUCT_REQUEST = "GET_SEARCH_PRODUCT_REQUEST";
const GET_SEARCH_PRODUCT_SUCCESS = "GET_SEARCH_PRODUCT_SUCCESS";
const GET_SEARCH_PRODUCT_FAILURE = "GET_SEARCH_PRODUCT_FAILURE";

export {
  GET_PRODUCT_REQUEST,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT_FAILURE,
  GET_PRODUCT_FILTER_REQUEST,
  GET_PRODUCT_FILTER_SUCCESS,
  GET_PRODUCT_FILTER_FAILURE,
  GET_SEARCH_PRODUCT_REQUEST,
  GET_SEARCH_PRODUCT_SUCCESS,
  GET_SEARCH_PRODUCT_FAILURE,
};
